[phases.setup]
nixPkgs = ["python311", "pip"]
aptPkgs = []

[phases.install] 
cmd = "pip install --no-cache-dir -r requirements.txt"

[phases.build]
cmd = "chmod +x start.sh"

[start]
cmd = "./start.sh"

[variables]
PYTHONPATH = "/app"
