"""Add landline and email to customers

Revision ID: 814cbfa3ea34
Revises: 
Create Date: 2025-09-09 11:25:26.101868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '814cbfa3ea34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add landline and email columns to customers table
    # Use try/except to handle cases where columns might already exist
    try:
        op.add_column('customers', sa.Column('landline', sa.String(20), nullable=True))
        print("✅ Added landline column to customers table")
    except Exception as e:
        print(f"⚠️ Could not add landline column (might already exist): {e}")
    
    try:
        op.add_column('customers', sa.Column('email', sa.String(255), nullable=True))
        print("✅ Added email column to customers table")
    except Exception as e:
        print(f"⚠️ Could not add email column (might already exist): {e}")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove landline and email columns from customers table
    try:
        op.drop_column('customers', 'email')
        print("✅ Removed email column from customers table")
    except Exception as e:
        print(f"⚠️ Could not remove email column: {e}")
    
    try:
        op.drop_column('customers', 'landline')
        print("✅ Removed landline column from customers table")
    except Exception as e:
        print(f"⚠️ Could not remove landline column: {e}")
    # ### end Alembic commands ###
